title: "Yasin Ilkagan Tepeli"
description: "Computational methods to discover cancer treatment opportunities"
author: "Yasin Ilkagan Tepeli"
url: ""  # set to https://<username>.github.io (no trailing slash) after you push
theme: minima

# Top navigation (now points to HTML pages)
header_pages:
  - publications.html
  - research.html
  - rest.html
  - contact.html

# Minima theme options
minima:
  skin: classic
  social_links:
    - { platform: github, user_url: "https://github.com/yitepeli" }
    - { platform: linkedin, user_url: "https://www.linkedin.com/in/yitepeli" }

# Clean URLs
permalink: pretty

# Markdown engine (kept for compatibility; Liquid still works in HTML with front matter)
markdown: kramdown
kramdown:
  input: GFM
